language: node_js
node_js:
- node
script: npm run build
after_success:
- sh .travis/deploy.sh 45.56.70.141 /home/apps/launch-club/micdsmitlaunch.club
before_install:
- openssl aes-256-cbc -K $encrypted_c8449bc2a4e0_key -iv $encrypted_c8449bc2a4e0_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
